lb:
  image: dockercloud/haproxy
  links:
    - version-server:version-server
  ports:
    - 80:80

version-server:
  image: willko/version-server
  environment:
    - VIRTUAL_HOST=http://*,https://*
  ports:
    - 7447:7447
  links:
    - db

db:
  image: postgres:9.6
  environment:
    - POSTGRES_DB=dev
    - POSTGRES_PASSWORD=dev
    - POSTGRES_USER=dev
  ports:
    - 5432:5432
