#!/usr/bin/env node


const version = '2.2.1';


const fs = require('fs');
const buildDate = new Date()

const out = {
  version: version,
  timestamp: buildDate.toISOString()
};

fs.writeFileSync('./cmdversions/version.json', JSON.stringify(out, null, 2));




